Repository codesquad-member-2020/issue-tracker-08, pull requests merged in 2020-06, with the labels that each got.

#10 [FE] 웹팩 기본 설정
  FE/.gitignore
  FE/babel.config.js
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.jsx
  FE/src/index.jsx
  FE/webpack.common.js
  FE/webpack.config.js
  FE/webpack.dev.js
  FE/webpack.prod.js
Labels: FE, Feature

#12 [FE] prettierre setting
  FE/.prettierrc.js
Labels: FE

#14 [FE] feat: 컴포넌트 구조 설계
  FE/src/components/CommentViewBox/CommentViewBox.jsx
  FE/src/components/FilterButton/FilterButton.jsx
  FE/src/components/FilterButton/FilterVerticalList.jsx
  FE/src/components/InputBox/CommentInputBox.jsx
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/components/NavigationButton/NavigationButton.jsx
  FE/src/views/CreateIssuePage/CreateIssuePage.jsx
  FE/src/views/CreateMilestonePage/CreateMilestonePage.jsx
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/LabelListPage/LabelListPage.jsx
  FE/src/views/LoginPage/LoginPage.jsx
  FE/src/views/MilestonePage/MilestonePage.jsx
  FE/src/views/SignupPage/SignupPage.jsx
Labels: FE

#19 [FE] 스타일 테마 작업
  FE/src/style/Button.js
  FE/src/style/GlobalStyle.js
  FE/src/style/Text.js
  FE/src/style/theme.js
Labels: FE

#21 [FE] 이슈 목록 화면 UI 구성
  FE/package-lock.json
  FE/package.json
  FE/src/components/NavigationButton/NavigationButton.jsx
  FE/src/style/Button.js
  FE/src/style/theme.js
  FE/src/views/IssueListPage/Issue/Issue.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
Labels: FE, Feature

#22 [FE] 로그인 화면 UI 구성
  FE/src/App.jsx
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/style/Button.js
  FE/src/style/Text.js
  FE/src/style/theme.js
  FE/src/views/LoginPage/LoginPage.jsx
Labels: FE, Feature

#28 [FE] 라우팅 처리 작업
  FE/.prettierrc.js
  FE/src/App.jsx
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/components/NavigationButton/NavigationButton.jsx
  FE/src/style/Button.js
  FE/src/style/theme.js
  FE/src/views/ErrorPage/ErrorPage.jsx
  FE/src/views/IssueListPage/Issue/Issue.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/LoginPage/LoginPage.jsx
  FE/webpack.common.js
Labels: FE, Feature

#31 [FE] 이슈 목록 화면 / 필터버튼 컴포넌트
  FE/package-lock.json
  FE/package.json
  FE/src/App.jsx
  FE/src/components/FilterButton/FilterButton.jsx
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/views/ErrorPage/ErrorPage.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/LoginPage/LoginPage.jsx
Labels: FE, Feature

#36 [FE] 테이블 재사용 컴포넌트 작성
  FE/src/components/Table/Table.jsx
  FE/src/views/IssueListPage/IssueListHeader/IssueListHeader.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/webpack.common.js
Labels: FE, Feature

#38 [FE] UI - FilterVerticalList (재사용 컴포넌트)
  FE/src/components/FilterButton/FilterButton.jsx
  FE/src/components/FilterButton/FilterVerticalList.jsx
  FE/src/views/CreateIssuePage/CreateIssuePage.jsx
  FE/src/views/IssueListPage/IssueListHeader/IssueListHeader.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
Labels: FE, Feature

#42 [FE] 이슈 상세 페이지(코멘트 / 필터버튼리스트)
  FE/src/components/CommentViewBox/CommentViewBox.jsx
  FE/src/style/Badge.js
  FE/src/style/theme.js
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueListPage/Issue/Issue.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
Labels: FE, Feature

#44 [FE] New Label 컴포넌트 작성
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/components/NavigationButton/NavigationButton.jsx
  FE/src/lib/getRandomColor.js
  FE/src/style/Badge.js
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/LabelListPage/CreateLabel/CreateLabel.jsx
  FE/src/views/LabelListPage/LabelListPage.jsx
Labels: FE, Feature

#45 [FE] 새로운 이슈 쓰기 페이지
  FE/package-lock.json
  FE/package.json
  FE/src/components/InputBox/CommentInputBox.jsx
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.css
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/components/InputBox/CommentInputBox/MarkdownConverted.jsx
  FE/src/style/Button.js
  FE/src/style/GlobalStyle.js
  FE/src/views/CreateIssuePage/CreateIssuePage.jsx
  FE/webpack.common.js
Labels: FE, Feature

#46 [FE] 라벨 목록 페이지
  FE/src/components/Header/Header.jsx
  FE/src/components/NavigationButton/NavigationButton.jsx
  FE/src/style/Text.js
  FE/src/views/CreateIssuePage/CreateIssuePage.jsx
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/LabelListPage/Label/Label.jsx
  FE/src/views/LabelListPage/LabelListHeader/LabelListHeader.jsx
  FE/src/views/LabelListPage/LabelListPage.jsx
Labels: FE, Feature

#49 [FE] 새로운 마일스톤 쓰기 페이지
  FE/src/App.jsx
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/components/NavigationButton/NavigationButton.jsx
  FE/src/views/CreateMilestonePage/CreateMilestonePage.jsx
  FE/src/views/CreateMilestonePage/DatePickers.jsx
  FE/src/views/LabelListPage/CreateLabel/CreateLabel.jsx
Labels: FE, Feature

#50 [FE] 마일스톤 목록 페이지 UI 작성
  FE/src/style/Text.js
  FE/src/views/MilestonePage/Milestone/Milestone.jsx
  FE/src/views/MilestonePage/MilestoneHeader/MilestoneHeader.jsx
  FE/src/views/MilestonePage/MilestonePage.jsx
Labels: FE, Feature

#53 [FE] 스타일 리팩토링
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.css
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/components/InputBox/CommentInputBox/MarkdownConverted.jsx
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/components/NavigationButton/NavigationButton.jsx
  FE/src/views/CreateMilestonePage/CreateMilestonePage.jsx
  FE/src/views/CreateMilestonePage/DatePickers.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
Labels: FE, Feature

#54 [FE] 스타일 리팩토링
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/components/Table/Table.jsx
  FE/src/views/CreateMilestonePage/CreateMilestonePage.jsx
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/LabelListPage/CreateLabel/CreateLabel.jsx
  FE/src/views/LabelListPage/LabelListPage.jsx
  FE/src/views/MilestonePage/Milestone/Milestone.jsx
  FE/src/views/MilestonePage/MilestonePage.jsx
Labels: FE, Feature

#61 [FE] issue list 화면 redux-thunk 연결
  FE/package-lock.json
  FE/package.json
  FE/src/App.jsx
  FE/src/components/Header/Header.jsx
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/components/NavigationButton/NavigationButton.jsx
  FE/src/constants/url.js
  FE/src/index.jsx
  FE/src/lib/api.js
  FE/src/lib/createRequestThunk.js
  FE/src/modules/index.js
  FE/src/modules/issue.js
  FE/src/modules/loading.js
  FE/src/style/Badge.js
  FE/src/style/Text.js
  FE/src/views/CreateIssuePage/CreateIssuePage.jsx
  FE/src/views/CreateMilestonePage/CreateMilestonePage.jsx
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueListPage/Issue/Issue.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/LabelListPage/LabelListPage.jsx
  FE/src/views/LoginPage/LoginPage.jsx
  FE/src/views/MilestonePage/Milestone/Milestone.jsx
  FE/src/views/MilestonePage/MilestonePage.jsx
  FE/webpack.common.js
Labels: FE, Feature

#60 [FE 리뷰요청] 2차 리뷰요청합니다.
  appspec.yml
  deploy-fe.sh
  package-lock.json
  package.json
  src/App.jsx
  src/components/CommentViewBox/CommentViewBox.jsx
  src/components/Header/Header.jsx
  src/components/InputBox/CommentInputBox.jsx
  src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  src/components/InputBox/CommentInputBox/MarkdownConverted.jsx
  src/components/InputBox/PersonalInputBox.jsx
  src/components/NavigationButton/NavigationButton.jsx
  src/components/Table/Table.jsx
  src/constants/url.js
  src/index.jsx
  src/lib/api.js
  src/lib/createRequestThunk.js
  src/lib/getRandomColor.js
  src/modules/index.js
  src/modules/issue.js
  src/modules/loading.js
  src/style/Badge.js
  src/style/Button.js
  src/style/GlobalStyle.js
  src/style/Text.js
  src/style/theme.js
  src/views/CreateIssuePage/CreateIssuePage.jsx
  src/views/CreateMilestonePage/CreateMilestonePage.jsx
  src/views/CreateMilestonePage/DatePickers.jsx
  src/views/IssueDetailPage/IssueDetailPage.jsx
  src/views/IssueListPage/Issue/Issue.jsx
  src/views/IssueListPage/IssueListPage.jsx
  src/views/LabelListPage/CreateLabel/CreateLabel.jsx
  src/views/LabelListPage/Label/Label.jsx
  src/views/LabelListPage/LabelListHeader/LabelListHeader.jsx
  src/views/LabelListPage/LabelListPage.jsx
  src/views/LoginPage/LoginPage.jsx
  src/views/MilestonePage/Milestone/Milestone.jsx
  src/views/MilestonePage/MilestoneHeader/MilestoneHeader.jsx
  src/views/MilestonePage/MilestonePage.jsx
  webpack.common.js
Labels: FE, Feature, fe 리뷰요청

#68 [FE] 라벨 페이지 - GET API 연결 / 상태관리
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/lib/api.js
  FE/src/lib/createRequestThunk.js
  FE/src/modules/index.js
  FE/src/modules/issue.js
  FE/src/modules/label.js
  FE/src/style/Button.js
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/LabelListPage/CreateLabel/CreateLabel.jsx
  FE/src/views/LabelListPage/Label/Label.jsx
  FE/src/views/LabelListPage/LabelListPage.jsx
Labels: FE, Feature

#74 [FE] 마일스톤 페이지 목록 데이터, 생성, 변경 API 연결
  FE/src/App.jsx
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/lib/api.js
  FE/src/modules/index.js
  FE/src/modules/milestone.js
  FE/src/views/CreateMilestonePage/CreateMilestonePage.jsx
  FE/src/views/CreateMilestonePage/DatePickers.jsx
  FE/src/views/MilestonePage/Milestone/Milestone.jsx
  FE/src/views/MilestonePage/MilestoneHeader/MilestoneHeader.jsx
  FE/src/views/MilestonePage/MilestonePage.jsx
Labels: FE

#77 [BE] 마일스톤 API 기능 구현 중
  BE/src/main/java/com/codesquad/issuetracker/common/BaseTimeEntity.java
  BE/src/main/java/com/codesquad/issuetracker/common/exception/ErrorMessage.java
  BE/src/main/java/com/codesquad/issuetracker/issue/domain/IssueRepository.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/application/MilestoneService.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/domain/MileStoneRepository.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/domain/MilestoneBoard.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/domain/MilestoneDTO.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/ui/MilestoneController.java
Labels: BE

#87 [BE] Milestone 엔티티 수정
  BE/src/main/java/com/codesquad/issuetracker/milestone/domain/Milestone.java
  BE/src/main/java/com/codesquad/issuetracker/milestone/ui/MilestoneController.java
Labels: BE

#89 [FE] OAuth 로그인 기능 구현
  FE/src/components/Header/Header.jsx
  FE/src/constants/url.js
  FE/src/lib/getCookieValue.js
  FE/src/views/LoginPage/LoginPage.jsx
Labels: FE, Feature

#92 [BE] DB 시간 데이터 KST로 변경
  BE/src/main/resources/application.yml
Labels: BE

#90 [BE] 로그인하지 않은 경우 예외 처리
  BE/src/main/java/com/codesquad/issuetracker/common/exception/ErrorMessage.java
  BE/src/main/java/com/codesquad/issuetracker/common/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issuetracker/common/exception/UnauthorizedException.java
  BE/src/main/java/com/codesquad/issuetracker/user/infrastructure/LoginInterceptor.java
Labels: BE

#95 [FE] 라벨 생성, 변경, 삭제 API 연결 구현
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/lib/api.js
  FE/src/lib/createRequestThunk.js
  FE/src/lib/getRandomColor.js
  FE/src/modules/index.js
  FE/src/modules/issue.js
  FE/src/modules/label.js
  FE/src/modules/milestone.js
  FE/src/style/theme.js
  FE/src/views/CreateMilestonePage/CreateMilestonePage.jsx
  FE/src/views/LabelListPage/CreateLabel/CreateLabel.jsx
  FE/src/views/LabelListPage/Label/Label.jsx
  FE/src/views/LabelListPage/LabelListPage.jsx
Labels: FE, Feature

#109 [FE] 회원가입, 로그인 기능 구현
  FE/src/components/Header/Header.jsx
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/constants/url.js
  FE/src/constants/validate.js
  FE/src/hooks/useDebounce.js
  FE/src/lib/api.js
  FE/src/lib/createRequestThunk.js
  FE/src/modules/index.js
  FE/src/modules/issue.js
  FE/src/modules/label.js
  FE/src/modules/milestone.js
  FE/src/modules/user.js
  FE/src/views/CreateMilestonePage/CreateMilestonePage.jsx
  FE/src/views/LoginPage/LoginPage.jsx
  FE/src/views/SignupPage/SignupPage.jsx
  FE/webpack.common.js
Labels: FE, Feature
