Repository codesquad-member-2020/issue-tracker-08, pull requests merged in 2020-07, with the labels that each got.

#124 [FE] 이슈 목록 UI(프로필사진, 댓글수)
  FE/src/components/CommentViewBox/CommentViewBox.jsx
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/style/Avatar.js
  FE/src/views/CreateMilestonePage/CreateMilestonePage.jsx
  FE/src/views/IssueListPage/Issue/Issue.jsx
  FE/src/views/MilestonePage/Milestone/Milestone.jsx
Labels: FE, Feature

#127 [FE] 이슈 상세 페이지 GET 연결
  FE/src/components/CommentViewBox/CommentViewBox.jsx
  FE/src/lib/api.js
  FE/src/modules/issue.js
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueListPage/Issue/Issue.jsx
Labels: FE, Feature

#129 [FE] Checkbox 선택 요소 상태관리
  FE/src/views/IssueListPage/Issue/Issue.jsx
  FE/src/views/IssueListPage/IssueListHeader/IssueListHeader.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
Labels: FE, Feature

#131 [BE] Comment의 최신 Id 값을 가져오는 레포지토리 메소드 오류 해결
  BE/src/main/java/com/codesquad/issuetracker/comment/application/CommentService.java
  BE/src/main/java/com/codesquad/issuetracker/comment/domain/CommentRepository.java
Labels: BE, bug

#132 [BE] 레코드 시간대를 KST로 변경
  BE/src/main/java/com/codesquad/issuetracker/IssueTrackerApplication.java
  BE/src/main/resources/application.yml
Labels: BE, bug

#133 [FE] 이슈 생성 기능 (API 연결)
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/lib/api.js
  FE/src/modules/issue.js
  FE/src/views/CreateIssuePage/CreateIssuePage.jsx
Labels: FE, Feature

#137 [FE] 코멘트 생성/삭제
  FE/src/components/CommentViewBox/CommentViewBox.jsx
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/components/InputBox/CommentInputBox/MarkdownConverted.jsx
  FE/src/lib/api.js
  FE/src/modules/issue.js
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueListPage/Issue/Issue.jsx
Labels: FE, Feature

#138 [FE] 코멘트 수정 기능
  FE/src/components/CommentViewBox/CommentViewBox.jsx
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/lib/api.js
  FE/src/modules/issue.js
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/LoginPage/LoginPage.jsx
  FE/webpack.dev.js
  FE/webpack.prod.js
Labels: FE, Feature

#139 [FE] 이슈 Open/Close 기능
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/lib/api.js
  FE/src/modules/issue.js
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
Labels: FE, Feature

#140 [FE] 이슈 제목 수정
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/lib/api.js
  FE/src/modules/issue.js
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueDetailPage/IssueDetailTitle/IssueDetailTitle.jsx
  FE/src/views/IssueListPage/Issue/Issue.jsx
Labels: FE, Feature

#143 [FE] 리팩토링(컴포넌트 나누기 + PR 리뷰 반영)
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/components/InputBox/CommentInputBox/CreateButtons/CreateButtons.jsx
  FE/src/components/InputBox/CommentInputBox/InputContent/InputContent.jsx
  FE/src/components/InputBox/CommentInputBox/SwitchButton/SwitchButton.jsx
  FE/src/components/InputBox/PersonalInputBox.jsx
  FE/src/views/CreateMilestonePage/CreateMilestoneButtons/CreateMilestoneButtons.jsx
  FE/src/views/CreateMilestonePage/CreateMilestoneContent/CreateMilestoneContent.jsx
  FE/src/views/CreateMilestonePage/CreateMilestonePage.jsx
  FE/src/views/CreateMilestonePage/CreateMilestoneTitle/CreateMilestoneTitle.jsx
  FE/src/views/IssueDetailPage/CommentList/CommentList.jsx
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/LabelListPage/LabelListPage.jsx
Labels: FE, Refactor

#147 [FE] 이슈 생성/수정 시에 체크 요소
  FE/package-lock.json
  FE/package.json
  FE/src/components/FilterButton/FilterButton.jsx
  FE/src/components/FilterButton/FilterVerticalList.jsx
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/index.jsx
  FE/src/lib/api.js
  FE/src/modules/index.js
  FE/src/modules/option.js
  FE/src/modules/user.js
  FE/src/views/CreateIssuePage/CreateIssuePage.jsx
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/LabelListPage/CreateLabel/CreateLabel.jsx
  FE/src/views/LabelListPage/Label/Label.jsx
Labels: FE, Feature

#151 [FE] 이슈 open/close 상태관리 + 리팩토링
  FE/src/components/FilterButton/FilterButton.jsx
  FE/src/components/FilterButton/FilterVerticalList.jsx
  FE/src/components/InputBox/CommentInputBox/CommentInputBox.jsx
  FE/src/components/InputBox/CommentInputBox/SwitchButton/SwitchButton.jsx
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueDetailPage/IssueDetailTitle/IssueDetailTitle.jsx
Labels: FE, Feature, Refactor

#155 [FE] Pagination
  FE/public/index.html
  FE/src/components/FilterButton/FilterVerticalList.jsx
  FE/src/lib/api.js
  FE/src/modules/issue.js
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/IssueListPage/Pagination/Pagination.jsx
Labels: FE, Feature

#157 [FE] 이슈 상세 페이지 - 본문 수정 기능
  FE/src/lib/api.js
  FE/src/modules/issue.js
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
Labels: FE, Feature

#158 [FE] 이슈 목록 화면 - 필터 데이터 연결
  FE/src/components/FilterButton/FilterVerticalList.jsx
  FE/src/views/IssueListPage/IssueListHeader/IssueListHeader.jsx
Labels: FE, Feature

#159 [FE] Code Spliting
  FE/package-lock.json
  FE/package.json
  FE/src/App.jsx
  FE/src/index.jsx
  FE/webpack.prod.js
Labels: FE, enhancement

#160 [FE] 이슈리스트 페이지 - 필터 기능
  FE/package-lock.json
  FE/src/components/FilterButton/FilterButton.jsx
  FE/src/components/FilterButton/FilterList.jsx
  FE/src/components/Table/HeaderSwitch/HeaderSwitch.jsx
  FE/src/lib/addQueryParams.js
  FE/src/modules/option.js
  FE/src/views/CreateIssuePage/CreateIssuePage.jsx
  FE/src/views/IssueDetailPage/IssueDetailPage.jsx
  FE/src/views/IssueListPage/IssueListHeader/IssueListHeader.jsx
  FE/src/views/IssueListPage/IssueListPage.jsx
  FE/src/views/IssueListPage/Pagination/Pagination.jsx
  FE/src/views/MilestonePage/MilestoneHeader/MilestoneHeader.jsx
  FE/src/views/MilestonePage/MilestonePage.jsx
Labels: FE, Feature
